package service

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"text/template"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
)

// RelationshipsMDGenerator writes ~/.solo/agents/<id>/workspace/RELATIONSHIPS.md
// for an agent.
type RelationshipsMDGenerator struct {
	pool          *pgxpool.Pool
	workspaceRoot string
}

func NewRelationshipsMDGenerator(pool *pgxpool.Pool, workspaceRoot string) *RelationshipsMDGenerator {
	return &RelationshipsMDGenerator{pool: pool, workspaceRoot: workspaceRoot}
}

type relationshipsDoc struct {
	AgentName      string
	UpdatedAt      string
	AssignsTo      []relRow
	AssignedFrom   []relRow
	Collaborators  []collabRow
	RecentActivity []activityRow
}

type relRow struct {
	OtherAgent  string
	Description string
	ActiveTasks int
	TotalTasks  int
	LastActive  string
	Instruction string
}

type collabRow struct {
	OtherAgent  string
	Description string
	Weight      float64
	Instruction string
}

type activityRow struct {
	At     string
	Action string
}

const relationshipsTpl = `# Agent @{{.AgentName}} — Relationships

> Auto-generated by Solo. Last updated: {{.UpdatedAt}}
> Read this before starting any task to check your colleagues and delegation criteria.

## Delegates to (@assigns_to from me)
{{range .AssignsTo}}
### @{{.OtherAgent}} (active: {{.ActiveTasks}}, total: {{.TotalTasks}})
{{if .Description}}{{.Description}}
{{end}}{{if .Instruction}}**DELEGATE when:**
{{.Instruction}}
{{else}}_(no delegation criteria set)_
{{end}}
{{end}}
## Delegated to me (@assigns_to to me)
{{range .AssignedFrom}}
### @{{.OtherAgent}} (active: {{.ActiveTasks}}, total: {{.TotalTasks}})
{{if .Description}}{{.Description}}
{{end}}{{if .Instruction}}**DELEGATE when:**
{{.Instruction}}
{{else}}_(no delegation criteria set)_
{{end}}
{{end}}
## Collaborators (@collaborates_with)
{{range .Collaborators}}
### @{{.OtherAgent}} (weight: {{.Weight}})
{{if .Description}}{{.Description}}
{{end}}{{if .Instruction}}**COLLABORATES when:**
{{.Instruction}}
{{else}}_(no collaboration criteria set)_
{{end}}
{{end}}
## Recent Activity (rolling 30 days)
{{range .RecentActivity}}- {{.At}} — {{.Action}}
{{end}}
`

func (g *RelationshipsMDGenerator) GenerateForAgent(ctx context.Context, agentID string) error {
	doc, err := g.collect(ctx, agentID)
	if err != nil {
		return err
	}
	var buf bytes.Buffer
	t := template.Must(template.New("rel").Parse(relationshipsTpl))
	if err := t.Execute(&buf, doc); err != nil {
		return fmt.Errorf("render template: %w", err)
	}
	dir := filepath.Join(g.workspaceRoot, agentID, "workspace")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("mkdir workspace: %w", err)
	}
	path := filepath.Join(dir, "RELATIONSHIPS.md")
	return os.WriteFile(path, buf.Bytes(), 0o644)
}

func (g *RelationshipsMDGenerator) collect(ctx context.Context, agentID string) (*relationshipsDoc, error) {
	doc := &relationshipsDoc{UpdatedAt: time.Now().Format("2006-01-02 15:04:05")}

	err := g.pool.QueryRow(ctx, `SELECT name FROM agents WHERE id = $1`, agentID).Scan(&doc.AgentName)
	if err != nil {
		return nil, fmt.Errorf("lookup agent name: %w", err)
	}

	rows, err := g.pool.Query(ctx, `
		SELECT a.name, COALESCE(a.description, ''), 0, 0, COALESCE(r.instruction, '')
		  FROM agent_relationships r
		  JOIN agents a ON a.id = r.to_agent_id
		 WHERE r.from_agent_id = $1 AND r.rel_type = 'assigns_to'
	`, agentID)
	if err != nil {
		return nil, fmt.Errorf("assigns_to from: %w", err)
	}
	for rows.Next() {
		var r relRow
		if err := rows.Scan(&r.OtherAgent, &r.Description, &r.ActiveTasks, &r.TotalTasks, &r.Instruction); err != nil {
			rows.Close()
			return nil, err
		}
		doc.AssignsTo = append(doc.AssignsTo, r)
	}
	rows.Close()

	rows, err = g.pool.Query(ctx, `
		SELECT a.name, COALESCE(a.description, ''), 0, 0, COALESCE(r.instruction, '')
		  FROM agent_relationships r
		  JOIN agents a ON a.id = r.from_agent_id
		 WHERE r.to_agent_id = $1 AND r.rel_type = 'assigns_to'
	`, agentID)
	if err != nil {
		return nil, fmt.Errorf("assigns_to to: %w", err)
	}
	for rows.Next() {
		var r relRow
		if err := rows.Scan(&r.OtherAgent, &r.Description, &r.ActiveTasks, &r.TotalTasks, &r.Instruction); err != nil {
			rows.Close()
			return nil, err
		}
		doc.AssignedFrom = append(doc.AssignedFrom, r)
	}
	rows.Close()

	rows, err = g.pool.Query(ctx, `
		SELECT a.name, COALESCE(a.description, ''), r.weight, COALESCE(r.instruction, '')
		  FROM agent_relationships r
		  JOIN agents a ON a.id = CASE WHEN r.from_agent_id = $1 THEN r.to_agent_id ELSE r.from_agent_id END
		 WHERE $1 IN (r.from_agent_id, r.to_agent_id)
		   AND r.rel_type = 'collaborates_with'
	`, agentID)
	if err != nil {
		return nil, fmt.Errorf("collaborates_with: %w", err)
	}
	for rows.Next() {
		var r collabRow
		if err := rows.Scan(&r.OtherAgent, &r.Description, &r.Weight, &r.Instruction); err != nil {
			rows.Close()
			return nil, err
		}
		doc.Collaborators = append(doc.Collaborators, r)
	}
	rows.Close()

	return doc, nil
}
