package service

import (
	"bytes"
	"context"
	"fmt"
	"text/template"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
)

type RelationshipsMDGenerator struct {
	pool *pgxpool.Pool
}

func NewRelationshipsMDGenerator(pool *pgxpool.Pool, _ string) *RelationshipsMDGenerator {
	return &RelationshipsMDGenerator{pool: pool}
}

type relationshipDoc struct {
	AgentName     string
	UpdatedAt     string
	AssignsTo     []relationshipDocRow
	AssignedFrom  []relationshipDocRow
	Collaborators []relationshipDocRow
}

type relationshipDocRow struct {
	OtherAgent  string
	Description string
	Weight      float64
	Instruction string
}

const relationshipsMDTemplate = `# Relationships for @{{.AgentName}}

Auto-generated by Solo. Last updated: {{.UpdatedAt}}

Read this before deciding whether to coordinate, delegate, claim, or collaborate on work.

## You coordinate
{{range .AssignsTo}}
- @{{.OtherAgent}}{{if .Description}} — {{.Description}}{{end}}{{if .Instruction}}
  - Delegate when: {{.Instruction}}{{end}}
{{else}}- None
{{end}}
## Coordinators for you
{{range .AssignedFrom}}
- @{{.OtherAgent}}{{if .Description}} — {{.Description}}{{end}}{{if .Instruction}}
  - They may delegate when: {{.Instruction}}{{end}}
{{else}}- None
{{end}}
## Collaborators
{{range .Collaborators}}
- @{{.OtherAgent}} (weight {{printf "%.1f" .Weight}}){{if .Description}} — {{.Description}}{{end}}{{if .Instruction}}
  - Collaborate when: {{.Instruction}}{{end}}
{{else}}- None
{{end}}
`

// GenerateForAgent validates that the relationship document can be produced.
// Only the daemon writes RELATIONSHIPS.md, under its Agent execution lock, using
// the exact channel/Team snapshot carried by the Run. Server-side relationship
// edits must never overwrite an active Run's workspace.
func (g *RelationshipsMDGenerator) GenerateForAgent(ctx context.Context, agentID string) error {
	_, err := g.RenderForAgent(ctx, agentID)
	return err
}

func (g *RelationshipsMDGenerator) collect(ctx context.Context, agentID string, channelIDs ...string) (*relationshipDoc, error) {
	channelID := ""
	if len(channelIDs) > 0 {
		channelID = channelIDs[0]
	}
	doc := &relationshipDoc{UpdatedAt: time.Now().Format("2006-01-02 15:04:05")}
	if err := g.pool.QueryRow(ctx, `SELECT name FROM agents WHERE id = $1`, agentID).Scan(&doc.AgentName); err != nil {
		return nil, err
	}

	assignsTo, err := g.queryRows(ctx, `
		SELECT a.name, COALESCE(a.description, ''), r.weight, COALESCE(r.instruction, '')
		  FROM agent_relationship_scopes r
		  JOIN agents a ON a.id = r.to_agent_id
		 WHERE r.from_agent_id = $1 AND r.rel_type = 'assigns_to' AND ($2='' OR r.channel_id::text=$2)
		 ORDER BY a.name
	`, agentID, channelID)
	if err != nil {
		return nil, fmt.Errorf("assigns_to: %w", err)
	}
	doc.AssignsTo = assignsTo

	assignedFrom, err := g.queryRows(ctx, `
		SELECT a.name, COALESCE(a.description, ''), r.weight, COALESCE(r.instruction, '')
		  FROM agent_relationship_scopes r
		  JOIN agents a ON a.id = r.from_agent_id
		 WHERE r.to_agent_id = $1 AND r.rel_type = 'assigns_to' AND ($2='' OR r.channel_id::text=$2)
		 ORDER BY a.name
	`, agentID, channelID)
	if err != nil {
		return nil, fmt.Errorf("assigned_from: %w", err)
	}
	doc.AssignedFrom = assignedFrom

	collaborators, err := g.queryRows(ctx, `
		SELECT a.name, COALESCE(a.description, ''), r.weight, COALESCE(r.instruction, '')
		  FROM agent_relationship_scopes r
		  JOIN agents a ON a.id = CASE WHEN r.from_agent_id = $1 THEN r.to_agent_id ELSE r.from_agent_id END
		 WHERE $1 IN (r.from_agent_id, r.to_agent_id) AND r.rel_type = 'collaborates_with' AND ($2='' OR r.channel_id::text=$2)
		 ORDER BY a.name
	`, agentID, channelID)
	if err != nil {
		return nil, fmt.Errorf("collaborators: %w", err)
	}
	doc.Collaborators = collaborators

	return doc, nil
}

func (g *RelationshipsMDGenerator) queryRows(ctx context.Context, query string, args ...any) ([]relationshipDocRow, error) {
	rows, err := g.pool.Query(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	out := []relationshipDocRow{}
	for rows.Next() {
		var row relationshipDocRow
		if err := rows.Scan(&row.OtherAgent, &row.Description, &row.Weight, &row.Instruction); err != nil {
			return nil, err
		}
		out = append(out, row)
	}
	return out, rows.Err()
}

// RenderForAgent is transported with each Run so remote Computers receive the same relationship snapshot.
func (g *RelationshipsMDGenerator) RenderForAgent(ctx context.Context, agentID string, channelIDs ...string) (string, error) {
	doc, err := g.collect(ctx, agentID, channelIDs...)
	if err != nil {
		return "", err
	}
	doc.UpdatedAt = "current dispatch"
	var buf bytes.Buffer
	if err := template.Must(template.New("relationships").Parse(relationshipsMDTemplate)).Execute(&buf, doc); err != nil {
		return "", err
	}
	return buf.String(), nil
}
