ALTER TABLE agents ADD COLUMN IF NOT EXISTS temperature FLOAT NOT NULL DEFAULT 0.7;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS max_tokens INT NOT NULL DEFAULT 4096;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS auto_join BOOLEAN NOT NULL DEFAULT false;
