ALTER TABLE messages
    ADD COLUMN seq BIGINT GENERATED BY DEFAULT AS IDENTITY;

CREATE UNIQUE INDEX idx_messages_seq ON messages(seq);
CREATE INDEX idx_messages_scope_seq
    ON messages(channel_id, thread_id, seq DESC)
    WHERE thinking_node_id IS NULL;

ALTER TABLE agent_runs
    ADD COLUMN freshness_seen_seq BIGINT,
    ADD COLUMN freshness_held_at TIMESTAMPTZ;
