package agent

// The system prompt is generated by BuildSystemPrompt (prompt.go) and delivered
// via --system-prompt-file (claude.go). No separate CLAUDE.md / AGENTS.md /
// GEMINI.md files are written — the system prompt file is the single source
// of truth (Slock-aligned).
